name: Config Sanity
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vision
    steps:
      - uses: actions/checkout@v4
      - name: Sanity check targets.json vs brief.schema
        run: |
          python3 tools/targets_sanity.py

